### ISSUE TITLE
The code should be refreshed to work with libgit2 v1.0.0

### ISSUE THREAD

**Issue by Apteryks** [magit/libegit2#92]
The current libgit2 commit used is old  (git describe --tags: v0.27.0-923-ge7873eb2c).  Attempting to use a recent version throws compilation errors such as:
```
[ 54%] Building C object src/CMakeFiles/egit2.dir/egit-reflog.c.o
cd /tmp/guix-build-emacs-libgit-20200223-1.6c3b892.drv-0/build/src && /gnu/store/x3jx25cd3q363mr7nbgzrhrv1vza6cf7-gcc-7.4.0/bin/gcc -Degit2_EXPORTS -isystem /include  -O2 -g -DNDEBUG -fPIC   -Wall -Wextra -std=gnu99 -o CMakeFiles/egit2.dir/egit-reflog.c.o   -c /tmp/guix-build-emacs-libgit-20200223-1.6c3b892.drv-0/emacs-libgit-20200223-1.6c3b892-checkout/src/egit-reflog.c
In file included from /tmp/guix-build-emacs-libgit-20200223-1.6c3b892.drv-0/emacs-libgit-20200223-1.6c3b892-checkout/src/interface.h:5:0,
                 from /tmp/guix-build-emacs-libgit-20200223-1.6c3b892.drv-0/emacs-libgit-20200223-1.6c3b892-checkout/src/egit-branch.c:3:
/tmp/guix-build-emacs-libgit-20200223-1.6c3b892.drv-0/emacs-libgit-20200223-1.6c3b892-checkout/src/symbols.h:30:5: error: unknown type name ‘git_indexcap_t’
     git_indexcap_t indexcap;
     ^~~~~~~~~~~~~~
```

**Comment by Apteryks** [comment]
Actually, this seems to be a problem on my end, as this type still exists in 0.99.0: https://libgit2.org/libgit2/#v0.99.0/type/git_indexcap_t

**Comment by Apteryks** [comment]
Commit 4e892ae5f is the one that broke git_index_capability_t.  It's just a bunch of renames, so I'll see if sed can make the compiler happy again.

**Comment by Apteryks** [comment]
With this branch here: https://github.com/Apteryks/libegit2/tree/allow-using-system-provided-libgit2 the only remaining compilation errors with v0.99.0 are:

```
[ 98%] Building C object src/CMakeFiles/egit2.dir/egit.c.o
cd /home/maxim/src/libegit2/build/src && /gnu/store/00n25m7rv4d6ddmjwznglnrrls6d6bmj-profile/bin/gcc -Degit2_EXPORTS -I/home/maxim/src/libegit2/libgit2/include  -O2 -g -DNDEBUG -fPIC   -Wall -Wextra -std=gnu99 -o CMakeFiles/egit2.dir/egit.c.o   -c /home/maxim/src/libegit2/src/egit.c
/home/maxim/src/libegit2/src/egit-util.c: In function ‘egit_cred_dup’:
/home/maxim/src/libegit2/src/egit-util.c:39:17: error: dereferencing pointer to incomplete type ‘git_credential {aka struct git_credential}’
     switch (cred->credtype) {
                 ^~
/home/maxim/src/libegit2/src/egit-util.c:42:14: error: dereferencing pointer to incomplete type ‘git_credential_ssh_key {aka struct git_credential_ssh_key}’
         if (c->privatekey)
              ^~
/home/maxim/src/libegit2/src/egit-util.c:52:60: error: dereferencing pointer to incomplete type ‘git_credential_userpass_plaintext {aka struct git_credential_userpass_plaintext}’
         return git_credential_userpass_plaintext_new(out, c->username, c->password);
                                                            ^~
/home/maxim/src/libegit2/src/egit-util.c:56:50: error: dereferencing pointer to incomplete type ‘git_credential_username {aka struct git_credential_username}’
         return git_credential_username_new(out, c->username);
                                                  ^~
/home/maxim/src/libegit2/src/egit-util.c:66:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[2]: *** [src/CMakeFiles/egit2.dir/build.make:560: src/CMakeFiles/egit2.dir/egit-util.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/maxim/src/libegit2/build'
make[1]: *** [CMakeFiles/Makefile2:289: src/CMakeFiles/egit2.dir/all] Error 2
make[1]: Leaving directory '/home/maxim/src/libegit2/build'
make: *** [Makefile:144: all] Error 2
```
Any ideas?

**Comment by TheBB** [comment]
Looks like some types changed to become opaque. Maybe there are some getters we can use instead?
